# react app
FROM node:12-alpine as build

WORKDIR /usr/src/client

COPY package*.json ./

RUN yarn

COPY . .

RUN yarn build

# nginx
FROM nginx:alpine

COPY --from=build /usr/src/client/build /usr/share/nginx/html
# --------- only for those using react router ----------
# if you are using react router 
# you need to overwrite the default nginx configurations
# remove default nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf
# replace with custom one
COPY ./nginx/nginx.conf /etc/nginx/conf.d
# --------- /only for those using react router ----------
# expose port 80 to the outer world
EXPOSE 80
# start nginx 
CMD ["nginx", "-g", "daemon off;"]